# Generated by Django 3.2.5 on 2022-04-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='sku',
            new_name='sku_id',
        ),
    ]
