# Generated by Django 3.2.5 on 2022-04-29 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_sku_ordergoods_sku_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='sku_id',
            new_name='sku',
        ),
    ]
