version: "3.9"

services:
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      #a bind mount 
      - type: bind
        source: ./db_data
        target: /var/lib/mysql
      - type: bind
        source: ./db_conf
        target: /etc/mysql/conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meiduo
      MYSQL_USER: meiduo
      MYSQL_PASSWORD: meiduo
    ports:
      - "33060:3306"

  redis:
    image: redis:6.2.5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "22345:8000"
    depends_on:
      - db
      - redis
      # - fdfs-worker

      #fastdfs as file storage system
      # fdfs-tracker:
      #   image: delron/fastdfs
      #   command: tracker
      #   volumes:
      #     - ./fdfs/tracker:/var/fdfs
      #   restart: always

      # fdfs-worker:
      #   image: delron/fastdfs
      #   command: storage
      #   volumes:
      #     - ./fdfs/storage:/var/fdfs
      #   environment:
      #     TRACKER_SERVER: meiduo-fdfs-tracker-1:22122
      #     GROUP_NAME: group1
      #   restart: always
      #   depends_on:
      #     - fdfs-tracker
      # ports:
      #   - "8888:8888"

      #Elasticsearch
  elasticsearch:
    image: delron/elasticsearch-ik:2.4.6-1.0
    # volumes:
    #   - ./elasticsearch/config:/usr/share/elasticsearch/config
    restart: always
    # ports:
    #   - "9200:9200"
