# Generated by Django 3.2.5 on 2022-03-02 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='models',
            new_name='mobile',
        ),
    ]
